apiVersion: v1
kind: Pod
metadata:
  name: preferred-pod
  namespace: default
spec:
  containers:
  - name: app
    image: nginx
    resources:
      requests:
        cpu: 1000
        memory: 15Gi

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "region"
            operator: In
            values: ["incorrect-value"]