apiVersion: v1
kind: Pod
metadata:
  name: medium-low-pod
  namespace: default
spec:
  containers:
  - name: app
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "size"
            operator: In
            values:
            - "medium"
            - "low"