apiVersion: v1
kind: Pod
metadata:
  name: not-important-pod
  namespace: default
spec:
  containers:
  - name: app
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "size"
            operator: NotIn
            values:
            - "high"