apiVersion: v1
kind: Pod
metadata:
  name: above-6-pod
  namespace: default
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: ratings
            operator: Gt
            values:
            - "6"
  containers:
  - name: app
    image: nginx