apiVersion: v1
kind: Pod
metadata:
  name: below-5-pod
  namespace: default
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: ratings
            operator: Lt
            values:
            - "5"
  containers:
  - name: app
    image: nginx