apiVersion: v1
kind: Pod
metadata:
  name: preferable-high-pod
  namespace: default
spec:
  containers:
  - name: app
    image: nginx
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: size
            operator: In 
            values:
            - low
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: size
            operator: In 
            values:
            - high