apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: app
    image: nginx
    resources:
      requests:
        memory: "6Gi"
        cpu: "1000m"
      limits:
        memory: "8Gi"
        cpu: "1000m"