apiVersion: v1
kind: Pod
metadata:
  name: no-priority-pod
  namespace: default
spec:
  containers:
  - name: app
    image: nginx
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
      limits:
        cpu: 500m
        memory: 500Mi
