---
apiVersion: v1
kind: Pod
metadata:
  name: high-priority-pod-2
  namespace: default
spec:
  containers:
  - name: app
    image: nginx
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
      limits:
        cpu: 500m
        memory: 500Mi
  priorityClassName: high-priority